### ISSUE TITLE
<ESC> in editing mode triggers Proof General autocomplete

### ISSUE THREAD

**Issue by chkl** [olivierverdier/spacemacs-coq#14]
First of all I would like to thank you for creating this layer. It makes using Proof General in spacemacs an absolutely pleasant experience.

Since a package upgrade last week I am experiencing a weird little bug that is also described here:
https://github.com/syl20bnr/spacemacs/issues/8853

Basically pressing the escape button triggers auto-completion, which is more annoying than it sounds as it makes it really hard to edit anything when any kind of variable name gets completed to tactics or similar...

I don't know how to fix the problem myself.

How to replicate:
Install the spacemacs-coq layer by cloning into `.emacs.d/private` (also works with a fresh spacemacs installation), add `coq` to the enabled layers. Open a file `test.v` enter o and press escape, the o gets replaced by "omega".

**Comment by sindikat** [comment]
Yep, I confirm that. Try to write `simpl`, then quickly press <kbd>fd</kbd> (or <kbd>ESC</kbd>). It will return to normal mode, but replace `simpl` with `simpl beta delta [] iota zeta`. Makes company-coq unusable for me.

**Comment by sindikat** [comment]
Yep, I confirm that. Try to write `simpl`, then quickly press <kbd>fd</kbd> (or <kbd>ESC</kbd>). It will return to normal mode, but replace `simpl` with `simpl beta delta [] iota zeta`. Makes company-coq unusable for me.

EDIT: I tracked the issue and it seems to have nothing to do with either `spacemacs-coq` or even `company-coq`, but with peculiarity of Evil itself (see [this patch](https://github.com/emacs-evil/evil/commit/c42dd5bed9fa400cd54de7236b4483b041554e4c)). The solution is to put

    (setq evil-want-abbrev-expand-on-insert-exit nil)

in your `dotspacemacs/user-init` (note, it's `init`, not `config`). Because this variable is only read on Evil load, putting it in `dotspacemacs/user-config` or even `(with-eval-after-load 'evil (setq evil-want-abbrev-expand-on-insert-exit nil))` will *not* work.

See also: https://github.com/ProofGeneral/PG/issues/174

**Comment by olivierverdier** [comment]
@sindikat amazing! Thanks a lot!
